# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-22 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='单词')),
                ('inter', models.CharField(max_length=256, verbose_name='解释')),
            ],
        ),
    ]
