# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-22 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='inter',
            field=models.CharField(max_length=256, null=True, verbose_name='解释'),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='word',
            field=models.CharField(max_length=50, null=True, verbose_name='单词'),
        ),
    ]
